export const actions = {
	ADD_PLAYER: 'ADD_PLAYER',
	REMOVE_PLAYER: 'REMOVE_PLAYER',
	START_GAME_REQUEST: 'START_GAME_REQUEST',
	START_GAME_DONE: 'START_GAME_DONE',
	ADD_PUNITIVE_CARD: 'ADD_PUNITIVE_CARD',
	REQUEST_ROOM_ID: 'SOCKET/REQUEST_ROOM_ID',
	SET_ROOM_ID: 'SET_ROOM_ID'
};

export const DUPLICATION_CARD = 4;
export const CARD_INDEX = 13;
export const HERO_NUMBER = 9;
export const BOSS_NUMBER = 4;

export const NUMBER_OF_HEROES_IN_A_GAME = 4;
export const NUMBER_OF_BOSSES_IN_A_GAME = 2;
