export const actions = {
    VIEW_PLAYER_CARD: 'VIEW_PLAYER_CARD',
    HIDE_CARD_VIEWER: 'HIDE_CARD_VIEWER',
    CHANGE_CARD: 'CHANGE_CARD',
    FLIP_CARD: 'FLIP_CARD',
    VIEW_FIRST_STOCK_CARD: 'VIEW_FIRST_STOCK_CARD',
    VIEW_WASTE_CARD_LIST: 'VIEW_WASTE_CARD_LIST',
    DROP_PLAYER_CARD: 'DROP_PLAYER_CARD',
    END_PLAYER_TURN: 'END_PLAYER_TURN'
};

export const defaultPlayerName = 'Player1';
